# aidcare_pipeline/crud.py
from sqlalchemy.orm import Session
from sqlalchemy import desc # For ordering
import uuid # For generating UUIDs
from datetime import datetime # For timestamps
from . import db_models as models # Using 'models' alias for clarity

# --- Patient CRUD ---
def create_patient(db: Session, full_name: str = None, dob: datetime = None, gender: str = None) -> models.Patient:
    patient_uuid_str = str(uuid.uuid4())
    db_patient = models.Patient(
        patient_uuid=patient_uuid_str, 
        full_name=full_name, 
        date_of_birth=dob, 
        gender=gender
        # created_at and updated_at will use server_default
    )
    db.add(db_patient)
    db.commit()
    db.refresh(db_patient)
    print(f"CRUD: Created Patient with UUID: {db_patient.patient_uuid}, DB ID: {db_patient.id}")
    return db_patient

def get_patient_by_uuid(db: Session, patient_uuid: str) -> models.Patient | None:
    return db.query(models.Patient).filter(models.Patient.patient_uuid == patient_uuid).first()

def get_patient_by_id(db: Session, patient_id: int) -> models.Patient | None: # Internal DB ID
    return db.query(models.Patient).filter(models.Patient.id == patient_id).first()

def get_patients(db: Session, skip: int = 0, limit: int = 100) -> list[models.Patient]:
    return db.query(models.Patient).order_by(models.Patient.id.desc()).offset(skip).limit(limit).all()

# --- PatientDocument CRUD ---
def create_patient_document(
    db: Session, 
    patient_id: int, 
    document_uuid: str, # Expect UUID to be generated by caller and passed in
    original_filename: str, 
    storage_path: str, 
    file_type: str
) -> models.PatientDocument:
    db_document = models.PatientDocument(
        patient_id=patient_id,
        document_uuid=document_uuid, # Use the provided UUID
        original_filename=original_filename,
        storage_path=storage_path,
        file_type=file_type,
        processing_status="queued" # Initial status
        # upload_timestamp will use server_default
    )
    db.add(db_document)
    db.commit()
    db.refresh(db_document)
    print(f"CRUD: Created PatientDocument with UUID: {db_document.document_uuid} for Patient ID: {patient_id}")
    return db_document

def get_patient_document_by_uuid(db: Session, document_uuid: str) -> models.PatientDocument | None:
    return db.query(models.PatientDocument).filter(models.PatientDocument.document_uuid == document_uuid).first()

def get_patient_documents(db: Session, patient_id: int, limit: int = 10) -> list[models.PatientDocument]:
    """Gets a list of documents for a patient, most recent first."""
    return db.query(models.PatientDocument)\
             .filter(models.PatientDocument.patient_id == patient_id)\
             .order_by(models.PatientDocument.upload_timestamp.desc())\
             .limit(limit)\
             .all()

def update_document_processing_status(
    db: Session, 
    document_uuid: str, 
    status: str, 
    extracted_text: str | None = None, 
    error_msg: str | None = None
) -> models.PatientDocument | None:
    db_document = get_patient_document_by_uuid(db, document_uuid=document_uuid)
    if db_document:
        db_document.processing_status = status
        db_document.processing_timestamp = datetime.utcnow() # Use UTC for server-side processing times
        if extracted_text is not None: # Allow empty string for extracted_text
            db_document.extracted_text = extracted_text
        if error_msg is not None:
            db_document.error_message = error_msg
        else: # Clear previous error if status is now good
            db_document.error_message = None 
            
        db.commit()
        db.refresh(db_document)
        print(f"CRUD: Updated PatientDocument UUID: {document_uuid}, Status: {status}")
        return db_document
    else:
        print(f"CRUD ERROR: PatientDocument with UUID {document_uuid} not found for update.")
    return None


# --- ConsultationSession CRUD ---
def create_consultation_session(
    db: Session, 
    patient_id: int, 
    mode: str, 
    session_uuid: str, # Expect UUID to be generated by caller
    audio_file_path: str = None, 
    transcript: str = None, 
    manual_context: str = None
) -> models.ConsultationSession:
    db_session = models.ConsultationSession(
        session_uuid=session_uuid, # Use the provided UUID
        patient_id=patient_id,
        mode=mode,
        audio_file_path=audio_file_path,
        transcript_text=transcript,
        manual_context_input=manual_context
        # timestamp_start will use server_default
    )
    db.add(db_session)
    db.commit()
    db.refresh(db_session)
    print(f"CRUD: Created ConsultationSession with UUID: {db_session.session_uuid} for Patient ID: {patient_id}")
    return db_session

def get_consultation_session_by_uuid(db: Session, session_uuid: str) -> models.ConsultationSession | None:
    return db.query(models.ConsultationSession).filter(models.ConsultationSession.session_uuid == session_uuid).first()

def update_consultation_session_results(
    db: Session, 
    session_uuid: str, 
    extracted_info: dict = None, 
    retrieved_docs_summary: list = None, # Changed name for clarity
    final_recommendation: dict = None,
    transcript_text: str = None # Allow updating transcript if it was processed later
):
    db_session = get_consultation_session_by_uuid(db, session_uuid=session_uuid)
    if db_session:
        if transcript_text is not None: # If transcript is being updated (e.g., if initial creation didn't have it)
            db_session.transcript_text = transcript_text
        if extracted_info is not None:
            db_session.extracted_info_json = extracted_info
        if retrieved_docs_summary is not None:
            db_session.retrieved_docs_summary_json = retrieved_docs_summary
        if final_recommendation is not None:
            db_session.final_recommendation_json = final_recommendation
        db.commit()
        db.refresh(db_session)
        print(f"CRUD: Updated ConsultationSession UUID: {session_uuid} with results.")
        return db_session
    else:
        print(f"CRUD ERROR: ConsultationSession UUID {session_uuid} not found for update.")
    return None

def get_patient_consultation_history(db: Session, patient_id: int, limit: int = 5) -> list[models.ConsultationSession]:
    """Gets a list of consultation sessions for a patient, most recent first."""
    return db.query(models.ConsultationSession)\
        .filter(models.ConsultationSession.patient_id == patient_id)\
        .order_by(models.ConsultationSession.timestamp_start.desc())\
        .limit(limit)\
        .all()